name : CI pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses : actions/checkout@v3
    - name : Set up Python 3.10
      uses : actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Cython and NumPy
      run: |
        pip install Cython numpy
    - name: Install PyStan
      run: |
        pip install pystan==2.19.1.1
    - name: Install remaining Python dependencies
      run: |
        pip install -r requirements.txt
    - name : Train and save pipeline
      run : python time_series_model/train_pipeline.py
    - uses : actions/upload-artifact@v2
      with:
        name: my-trained-pipeline
        path : time_series_model/trained_models/*.pkl

  build:
    needs: [train]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses : actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-pipeline
        path: time_series_model/trained_models
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v2
      with:
        name: my-build-package
        path: dist/*.whl
        retention-days: 1

  push-image:
    needs: [ train, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: my-build-package
          path: time_series_model_api

      - name: Login to Docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image for Fastapi app
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker build . -f Dockerfile -t $DOCKER_USER/time-series-fastapi:latest

      - name: Push the Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker push $DOCKER_USER/time-series-fastapi

      - name: Logout to Docker hub
        run: docker logout
